# Generated by Django 4.1 on 2022-08-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Показание датчика', 'verbose_name_plural': 'Показания датчиков'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Сенсор', 'verbose_name_plural': 'Сенсоры'},
        ),
    ]
